queue_rules:
  - name: default
    routing_conditions:
      - check-success=lab-ci
    conditions:
      - check-success=lab-ci
    merge_method: squash

pull_request_rules:
  - name: queue labeled pull requests
    conditions:
      - label=merge-queue
    actions:
      queue:
        name: default
